appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.1.27:8123
      ha_key: Ics@12345
hadashboard:
  dashboard_dir: /home/homeassistant/.homeassistant/conf/dashboards
  dash_url: http://192.168.1.27:5050

