- alias: auto_light_turn_on_ics
  trigger:
  - entity_id: binary_sensor.xiaomi_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_ics_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.turnon_light_ics
- alias: auto_light_turn_on_cps
  trigger:
  - entity_id: sensor.camera_tech_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_cps_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.turnon_light_day_cps
- alias: auto_light_turn_on_account
  trigger:
  - entity_id: sensor.camera_account_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_account_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.turnon_light_day_account
- alias: auto_light_turn_on_recep
  trigger:
  - entity_id: sensor.camera_recep_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_recep_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_lunch_boolean
        state: 'on'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','off')) %}
          script.turnon_light_day_recep
        {% elif (is_state('sensor.time_night_boolean','on') or ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','on')))) %}
          script.turnon_light_night_recep
        {% endif %}
- alias: auto_light_turn_off_ics
  trigger:
  - entity_id: binary_sensor.xiaomi_motion_sensor
    for:
      minutes: 1
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.light_ics_status
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.time_night_boolean
          state: 'on'
        - condition: state
          entity_id: sensor.time_lunch_boolean
          state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.turnoff_light_ics
- alias: auto_light_turn_off_cps
  trigger:
  - entity_id: sensor.camera_tech_motion
    for:
      minutes: 1
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.light_cps_status
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.time_work_boolean
          state: 'on'
        - condition: state
          entity_id: sensor.time_night_boolean
          state: 'on'
        - condition: state
          entity_id: sensor.time_lunch_boolean
          state: 'on'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
         {% if (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','off')) %}
          script.turnoff_light_day_cps
         {% elif (is_state('sensor.time_night_boolean','on') or ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','on')))) %}
          script.turnoff_light_night_cps
         {% endif %}
- alias: auto_light_turn_off_account
  trigger:
  - entity_id: sensor.camera_account_motion
    for:
      minutes: 1
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_account_status
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
         {% if (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','off')) %}
          script.turnoff_light_day_account
         {% elif (is_state('sensor.time_night_boolean','on') or ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','on')))) %}
          script.turnoff_light_night_account
         {% endif %}
- alias: auto_light_turn_off_recep
  trigger:
  - entity_id: sensor.camera_recep_motion
    for:
      minutes: 1
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_recep_status
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
         {% if (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','off')) %}
          script.turnoff_light_day_recep
         {% elif (is_state('sensor.time_night_boolean','on') or ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','on')))) %}
          script.turnoff_light_night_recep
         {% endif %}
- alias: auto_turn_on_automation_at_lunch_time
  trigger:
  - platform: time
    at: '12:00:10'
  action:
  - service: script.turn_on
    data:
      entity_id: script.turnon_automation_at_lunch
- alias: auto_turn_on_automation_at_night_time
  trigger:
  - platform: time
    at: '17:00:10'
  action:
  - service: script.turn_on
    data:
      entity_id: script.turnon_automation_at_lunch