- id: '1530973188375'
  alias: auto_light_turn_on_cps
  trigger:
  - entity_id: sensor.camera_tech_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_cps_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - data:
      event: turn_on_cps
    service: ifttt.trigger
  - data:
      entity_id: input_boolean.light_cps_status
    service: input_boolean.turn_on
- id: '1530973462333'
  alias: auto_light_turn_on_account
  trigger:
  - entity_id: sensor.camera_account_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_account_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - data:
      event: turn_on_account
    service: ifttt.trigger
  - data:
      entity_id: input_boolean.light_account_status
    service: input_boolean.turn_on
- id: '1530973588722'
  alias: auto_light_turn_on_recep
  trigger:
  - entity_id: sensor.camera_recep_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.light_recep_status
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.time_work_boolean
        state: 'on'
      - condition: state
        entity_id: sensor.time_night_boolean
        state: 'on'
  action:
  - data: {}
    service: script.turnon_light_day_recep
- id: '1530973778241'
  alias: auto_light_turn_off_day_cps
  trigger:
  - entity_id: sensor.camera_tech_motion
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_work_boolean
    state: 'on'
  action:
  - service: script.turnoff_light_day_cps
- id: '1530973778242'
  alias: auto_light_turn_off_night_cps
  trigger:
  - entity_id: sensor.camera_tech_motion
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_night_boolean
    state: 'on'
  action:
  - service: script.turnoff_light_night_cps
- id: '1530973877547'
  alias: auto_light_turn_off_day_account
  trigger:
  - entity_id: sensor.camera_account_motion
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_work_boolean
    state: 'on'
  action:
  - alias: ''
    data: {}
    service: script.turnoff_light_day_account
- id: '1530973877548'
  alias: auto_light_turn_off_night_account
  trigger:
  - entity_id: sensor.camera_account_motion
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_night_boolean
    state: 'on'
  action:
  - alias: ''
    data: {}
    service: script.turnoff_light_night_account
- id: '1531018872722'
  alias: auto_light_turn_off_day_recep
  trigger:
  - entity_id: sensor.camera_motion_all
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_work_boolean
    state: 'on'
  action:
  - data: {}
    service: script.turnoff_light_day_recep
- id: '1531018872723'
  alias: auto_light_turn_off_night_recep
  trigger:
  - entity_id: sensor.camera_motion_all
    for:
      minutes: 2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.time_night_boolean
    state: 'on'
  action:
  - data: {}
    service: script.turnoff_light_night_recep
