- alias: auto_light_turn_on_ics
  trigger:
    platform: state
    entity_id: sensor.trigger_turn_on_light_ics
    from: 'off'
    to: 'on'
  condition: 
    - condition: state
      entity_id: switch.light_sonoff_4chpro_ics
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.light_sonoff_4chpro_ics
- alias: auto_light_turn_off_ics
  trigger:
  - platform: state
    entity_id: sensor.trigger_turn_off_light_ics
    to: 'on'
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: switch.light_sonoff_4chpro_ics
      state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.light_sonoff_4chpro_ics
- alias: motion_turn_off_ics
  trigger:
  - platform: state
    entity_id: switch.light_sonoff_4chpro_ics
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.light_sonoff_4chpro_ics
    from: 'on'
    to: 'off'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','off') and is_state('switch.light_sonoff_4chpro_ics','off')) %}
          script.turnoff_motion_light_day_ics
        {% elif (is_state('sensor.time_night_boolean','on') or ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','on')))) %}
          script.turnoff_motion_light_night_ics
        {% endif %}

- alias: auto_light_turn_on_cps
  trigger:
    platform: state
    entity_id: sensor.trigger_turn_on_light_cps
    from: 'off'
    to: 'on'
  condition: 
    - condition: state
      entity_id: switch.light_sonoff_4chpro_cps
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.light_sonoff_4chpro_cps
- alias: auto_light_turn_off_cps
  trigger:
  - platform: state
    entity_id: sensor.trigger_turn_off_light_cps
    to: 'on'
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: switch.light_sonoff_4chpro_cps
      state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.light_sonoff_4chpro_cps
- alias: motion_turn_off_cps
  trigger:
  - platform: state
    entity_id: switch.light_sonoff_4chpro_cps
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.light_sonoff_4chpro_cps
    from: 'on'
    to: 'off'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','off') and is_state('switch.light_sonoff_4chpro_cps','off')) and is_state('switch.light_sonoff_4chpro_cps','off')) %}
          script.turnoff_motion_off_day_cps
        {% elif ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','off') and is_state('switch.light_sonoff_4chpro_cps','off')) and is_state('switch.light_sonoff_4chpro_cps','on')) %}
          script.turnoff_motion_on_day_cps
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','on'))) and is_state('switch.light_sonoff_4chpro_cps','off')) %}
          script.turnoff_motion_off_night_cps
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_tech_irled','on'))) and is_state('switch.light_sonoff_4chpro_cps','on')) %}
          script.turnoff_motion_on_day_cps
        {% endif %}

- alias: auto_light_turn_on_account
  trigger:
    platform: state
    entity_id: sensor.trigger_turn_on_light_account
    from: 'off'
    to: 'on'
  condition: 
    - condition: state
      entity_id: switch.light_sonoff_t1_account
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.light_sonoff_t1_account
- alias: auto_light_turn_off_account
  trigger:
  - platform: state
    entity_id: sensor.trigger_turn_off_light_account
    to: 'on'
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: switch.light_sonoff_t1_account
      state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.light_sonoff_t1_account
- alias: motion_turn_off_account
  trigger:
  - platform: state
    entity_id: switch.light_sonoff_t1_account
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.light_sonoff_t1_account
    from: 'on'
    to: 'off'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','off') and is_state('switch.light_sonoff_t1_account','off')) and is_state('switch.light_sonoff_t1_account','off')) %}
          script.turnoff_motion_off_day_account
        {% elif ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','off') and is_state('switch.light_sonoff_t1_account','off')) and is_state('switch.light_sonoff_t1_account','on')) %}
          script.turnoff_motion_on_day_account
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','on'))) and is_state('switch.light_sonoff_t1_account','off')) %}
          script.turnoff_motion_off_night_account
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_account_irled','on'))) and is_state('switch.light_sonoff_t1_account','on')) %}
          script.turnoff_motion_on_day_account
        {% endif %}

- alias: auto_light_turn_on_recep
  trigger:
    platform: state
    entity_id: sensor.trigger_turn_on_light_recep
    from: 'off'
    to: 'on'
  condition: 
    - condition: state
      entity_id: switch.light_sonoff_4chpro_recep
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.light_sonoff_4chpro_recep
- alias: auto_light_turn_off_recep
  trigger:
  - platform: state
    entity_id: sensor.trigger_turn_off_light_recep
    to: 'on'
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: switch.light_sonoff_4chpro_recep
      state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.light_sonoff_4chpro_recep
- alias: motion_turn_off_recep
  trigger:
  - platform: state
    entity_id: switch.light_sonoff_4chpro_recep
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.light_sonoff_4chpro_recep
    from: 'on'
    to: 'off'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >-
        {% if ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','off') and is_state('switch.light_sonoff_4chpro_recep','off')) and is_state('switch.light_sonoff_4chpro_recep','off')) %}
          script.turnoff_motion_off_day_recep
        {% elif ((is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','off') and is_state('switch.light_sonoff_4chpro_recep','off')) and is_state('switch.light_sonoff_4chpro_recep','on')) %}
          script.turnoff_motion_on_day_recep
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','on'))) and is_state('switch.light_sonoff_4chpro_recep','off')) %}
          script.turnoff_motion_off_night_recep
        {% elif ((is_state('sensor.time_night_boolean','on') or (is_state('sensor.time_work_boolean','on') and is_state('sensor.camera_recep_irled','on'))) and is_state('switch.light_sonoff_4chpro_recep','on')) %}
          script.turnoff_motion_on_night_recep
        {% endif %}

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff1/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff1/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff1/power3"
        payload: "" 
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/power3"
        payload: "" 
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/power4"
        payload: ""