- platform: foscam
  name: Camera Technical
  ip: 192.168.1.21
  port: 88
  username: ics
  password: Ics@12345
- platform: foscam
  name: Camera Reception
  ip: 192.168.1.22
  port: 88
  username: ics
  password: Ics@12345
- platform: foscam
  name: Camera Account
  ip: 192.168.1.23
  port: 88
  username: ics
  password: Ics@12345