media_player.officer_speaker:
  config_entry_id: 6e0446e3806945f58bf8d95efef1f382
  name:
  platform: cast
  unique_id: 74270cd8-3b85-eb2b-9a08-bd2d0dcde86d
light.light_meeting_table:
  config_entry_id:
  name:
  platform: lifx
  unique_id: d0:73:d5:31:4c:69
media_player.home_mini:
  config_entry_id: 95efdfc435b3414c9852d2f5ac6099fe
  name:
  platform: cast
  unique_id: 85ba8c6b-bb21-81dd-2548-840122394eb5
media_player.home_group:
  config_entry_id: 95efdfc435b3414c9852d2f5ac6099fe
  name:
  platform: cast
  unique_id: 1aff4c07-7692-450f-8f44-c8837b734689
sensor.0x00158d0001c16749_temperature:
  config_entry_id:
  name:
  platform: mqtt
  unique_id: 0x00158d0001c16749_temperature_zigbee2mqtt
sensor.0x00158d0001c16749_humidity:
  config_entry_id:
  name:
  platform: mqtt
  unique_id: 0x00158d0001c16749_humidity_zigbee2mqtt
sensor.0x00158d0001f54eaf_power:
  config_entry_id:
  name:
  platform: mqtt
  unique_id: 0x00158d0001f54eaf_power_zigbee2mqtt
switch.0x00158d0001f54eaf_switch:
  config_entry_id:
  name: Xiaomi_Zigbee_Plug
  platform: mqtt
  unique_id: 0x00158d0001f54eaf_switch_zigbee2mqtt
media_player.googlehome6371:
  config_entry_id: 6e0446e3806945f58bf8d95efef1f382
  name:
  platform: cast
  unique_id: 5500e58a-cb61-89ff-0574-c6edcb11ed78
media_player.googlehome4493:
  config_entry_id: 6e0446e3806945f58bf8d95efef1f382
  name:
  platform: cast
  unique_id: 2141734d-0bcb-7ff7-6559-173fbe958feb
