  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.task1
      - group.task2
  task1:
    name: Home View
    view: yes
    entities:
      - input_boolean.lifx_contact
  task2:
    name: Camera View
    view: yes
    entities:
      - camera.foscam_camera