# Sensors Configuration
- platform: yr
# Camera Sensors
- platform: command_line
  name: "Camera recep motion"
  command: 'curl -k --silent "https://192.168.1.22:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=motionDetectAlarm>).*?(?=</motionDetectAlarm>)"'
  value_template: >-
    {%- if value == "0" -%}
      disabled
    {%- elif value == "1" -%}
      off
    {%- elif value == "2" -%}
      on
    {%- endif -%}
  scan_interval: 2
- platform: command_line
  name: "Camera account motion"
  command: 'curl -k --silent "https://192.168.1.23:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=motionDetectAlarm>).*?(?=</motionDetectAlarm>)"'
  value_template: >-
    {%- if value == "0" -%}
      disabled
    {%- elif value == "1" -%}
      off
    {%- elif value == "2" -%}
      on
    {%- endif -%}
  scan_interval: 2
- platform: command_line
  name: "Camera tech motion"
  command: 'curl -k --silent "https://192.168.1.21:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=motionDetectAlarm>).*?(?=</motionDetectAlarm>)"'
  value_template: >-
    {%- if value == "0" -%}
      disabled
    {%- elif value == "1" -%}
      off
    {%- elif value == "2" -%}
      on
    {%- endif -%}
  scan_interval: 2
- platform: command_line
  name: "Camera recep IrLed"
  command: 'curl -k --silent "https://192.168.1.22:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  value_template: >-
    {%- if value == "0" -%}
      off
    {%- elif value == "1" -%}
      on
    {%- endif -%}
  scan_interval: 30
- platform: command_line
  name: "Camera account IrLed"
  command: 'curl -k --silent "https://192.168.1.23:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  value_template: >-
    {%- if value == "0" -%}
      off
    {%- elif value == "1" -%}
      on
    {%- endif -%}
  scan_interval: 30
- platform: command_line
  name: "Camera Tech IrLed"
  command: 'curl -k --silent "https://192.168.1.21:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ics&pwd=Ics@12345" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  value_template: >-
    {%- if value == "0" -%}
      off
    {%- elif value == "1" -%}
      on
    {%- endif -%}
  scan_interval: 30
- platform: template
  sensors:
    camera_motion_all:
      friendly_name: "Camera motion all"
      value_template: >-
        {%- if ((is_state('sensor.camera_account_motion', 'off') and is_state('sensor.camera_recep_motion', 'off') and is_state('binary_sensor.xiaomi_motion_sensor','off') and is_state('sensor.camera_tech_motion', 'off') and (now().weekday() < 6)) or (is_state('sensor.camera_recep_motion', 'off') and (now().weekday() == 6))) -%}
          off
        {%- else -%}
          on
        {%- endif -%}
  scan_interval: 2

# Sensors for check time work
- platform: template
  sensors:
    time_work_boolean:
      friendly_name: "Sensor for time work"
      value_template: >-
        {%- if ((now().hour >= 6) and (now().hour < 12) or (now().hour >= 13) and (now().hour < 18)) -%}
          on
        {%- else -%}
          off
        {%- endif -%}
  scan_interval: 5
# Sensors for check time night
- platform: template
  sensors:
    time_night_boolean:
      friendly_name: "Sensor for time night"
      value_template: >-
        {%- if ((now().hour >= 18) or (now().hour < 6)) -%}
          on
        {%- else -%}
          off
        {%- endif -%}
  scan_interval: 5
# Sensors for check time lunch
- platform: template
  sensors:
    time_lunch_boolean:
      friendly_name: "Sensor for time lunch"
      value_template: >-
        {%- if ((now().hour >= 11) and (now().hour < 13)) -%}
          on
        {%- else -%}
          off
        {%- endif -%}
  scan_interval: 5

#Sensor for time
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# Sensors for weather
- platform: darksky
  api_key: f705d36f9e5cdaa205053335db64ec5a
  forecast array: 1
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index

# Xiaomi Sensors for get batterry
- platform: mqtt
  name: "xiaomi_zigbee_motion_battery"
  state_topic: "zigbee2mqtt/xiaomi_motion_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: '%'
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: "xiaomi_zigbee_motion_voltage"
  state_topic: "zigbee2mqtt/xiaomi_motion_sensor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: 'V'
  value_template: "{{ value_json.voltage }}"
- platform: mqtt
  name: "xiaomi_zigbee_tempt_battery"
  state_topic: "zigbee2mqtt/xiaomi_zigbee_tempt"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: '%'
  value_template: "{{ value_json.battery }}"
- platform: mqtt
  name: "xiaomi_zigbee_tempt_voltage"
  state_topic: "zigbee2mqtt/xiaomi_zigbee_tempt"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: 'V'
  value_template: "{{ value_json.voltage }}"

# Mobile Phone Sensors for get batterry
- platform: mqtt
  state_topic: "owntracks/username/anh"
  name: "ICS ANHLD AndroidPhone Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery
  scan_interval: 60