- platform: mqtt
  name: "light_sonoff_t1_account_1"
  state_topic: "stat/sonoff1/POWER1"
  command_topic: "cmnd/sonoff1/POWER1"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_t1_plan"
  state_topic: "stat/sonoff1/POWER2"
  command_topic: "cmnd/sonoff1/POWER2"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_t1_account_2"
  state_topic: "stat/sonoff1/POWER3"
  command_topic: "cmnd/sonoff1/POWER3"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_4chpro_ics"
  state_topic: "stat/sonoff4chpro/POWER1"
  command_topic: "cmnd/sonoff4chpro/POWER1"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_4chpro_cps"
  state_topic: "stat/sonoff4chpro/POWER2"
  command_topic: "cmnd/sonoff4chpro/POWER2"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_4chpro_recep"
  state_topic: "stat/sonoff4chpro/POWER3"
  command_topic: "cmnd/sonoff4chpro/POWER3"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "light_sonoff_4chpro_account"
  state_topic: "stat/sonoff4chpro/POWER4"
  command_topic: "cmnd/sonoff4chpro/POWER4"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: template
  switches:
    light_sonoff_t1_account:
      value_template: "{{ is_state('switch.light_sonoff_t1_account_1', 'on') or is_state('switch.light_sonoff_t1_account_2', 'on') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.turn_on_switch_account
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.turn_off_switch_account